name: path-of-the-python
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uv run fastapi dev --host 0.0.0.0 main.py
    environment:
      - PYTHONUNBUFFERED=1
