name: path-of-the-python
services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "8002:3000"
    volumes:
      - ./frontend:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
