[project]
name = "path-of-the-python"
version = "0.1.0"
description = "A text-based maze adventure powered by AI"
authors = [
  { name = "Jeremy" }
]
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]"
]
